boot_command          = "<tab> text inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/rockylinux/8/ks.cfg<enter><wait10><wait10><esc>"
cpus                  = "4"
cloud_init_path       = "extra/files/cloud-init/rhel/generic/cloud.cfg"
disk_interface        = "virtio"
disk_size             = "60G"
format                = "qcow2"
headless              = false
iso_checksum          = "sha256:7b8bdfe189cf24ae5c2d6a88f7a0b5f3012d23f9332c47943d538b4bc03a3704"
iso_url               = "https://ftp.psnc.pl/linux/rockylinux/8.8/isos/x86_64/Rocky-x86_64-dvd1.iso"
memory                = "4096"
net_device            = "virtio-net"
shutdown_command      = "sudo -S /sbin/halt -h -p"
ssh_password          = "password"
ssh_username          = "root"
template              = "rockylinux-8.8-x86_64"
