boot_command          = "<tab> text inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/almalinux/9/kvm/ks.cfg<enter><wait10><wait10><esc>"
cpus                  = "4"
cloud_init_path       = "extra/files/cloud-init/rhel/generic/cloud.cfg"
disk_interface        = "virtio"
disk_size             = "60G"
format                = "qcow2"
headless              = false
iso_checksum          = "sha256:6617436f8f2ee5408ff448a4eedce4ce61e2fdb3153a646b875010256bc9fd6b"
iso_url               = "https://repo.almalinux.org/vault/9.0/isos/x86_64/AlmaLinux-9.0-x86_64-dvd.iso"
memory                = "4096"
net_device            = "virtio-net"
shutdown_command      = "sudo -S /sbin/halt -h -p"
ssh_password          = "password"
ssh_username          = "root"
template              = "almalinux-9.0-x86_64"
