---
name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on:
  push:
  pull_request:
    branches: [master, main, develop]
  workflow_dispatch:

permissions:
  actions: read
  attestations: read
  contents: read
  deployments: read
  discussions: read
  issues: read
  packages: write
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: write
  checks: write
  id-token: write

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  super-lint:
    # Name the Job
    name: Lint code base
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v7 # zizmor: ignore[unpinned-uses]
        with:
          fetch-depth: 0
          persist-credentials: false
      # Runs the Super-Linter action
      - name: Run Super-Linter
        uses: super-linter/super-linter/slim@v8.7.0 # zizmor: ignore[unpinned-uses]
        env:
          LINTER_RULES_PATH: .github/linters
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_PUSH_EVENT: ${{ github.event.forced }}
          VALIDATE_ALL_CODEBASE: ${{ github.event_name != 'pull_request' }}
          FILTER_REGEX_EXCLUDE: ".*extra/.*"
          VALIDATE_JSCPD: false
          VALIDATE_TERRAGRUNT: false
          VALIDATE_GITLEAKS: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_BIOME_LINT: false
          VALIDATE_BLACK: false
